services:
  - type: web
    name: credmar
    env: node
    buildCommand: yarn install && yarn prisma generate && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: America/Sao_Paulo