services:
  - type: web
    name: credmar
    env: node
    buildCommand: npm install && npm run db:generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: America/Sao_Paulo